[package]
edition = "2024"
name = "woodox"
version = "0.1.0"

[dependencies]
woodox-lib = { path = "../../library" }

rtic = { version = "2", features = ["thumbv8main-backend"] }
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "1"
embedded-time = "0.12"

defmt = "1"
defmt-rtt = "1"
panic-probe = { version = "1", features = ["print-defmt"] }

usbd-human-interface-device = "0.6"
usb-device = "0"
fugit = "0.3.9"
frunk_core = { version = "0.4", default-features = false }
packed_struct = { version = "0", default-features = false }

rp235x-hal = { git = "https://github.com/rp-rs/rp-hal", features = ["binary-info", "critical-section-impl", "rt", "defmt", "qfn80"] }

# ws2812-pio = "0.9"
# smart-leds = "0.4"

[dev-dependencies]
embedded-hal-mock = "0.11"

[features]
default = ["woodox"]

# Timer to gather some benchmarks during runtime
timers = []

macropad = []
woodox = []
